/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/website/aboutMe.vue')['default']
    FeaturedWorks: typeof import('./src/components/website/featuredWorks.vue')['default']
    HeroBanner: typeof import('./src/components/website/heroBanner.vue')['default']
    HowDoWork: typeof import('./src/components/website/howDoWork.vue')['default']
    LetsTalk: typeof import('./src/components/website/letsTalk.vue')['default']
    MainHeadingText: typeof import('./src/components/website/headings/mainHeadingText.vue')['default']
    MyExperiences: typeof import('./src/components/website/myExperiences.vue')['default']
    MySkills: typeof import('./src/components/website/mySkills.vue')['default']
    MyTechStacks: typeof import('./src/components/website/myTechStacks.vue')['default']
    MyWork: typeof import('./src/components/website/myWork.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubHeadingText: typeof import('./src/components/website/headings/subHeadingText.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UColorModeSwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/color-mode/ColorModeSwitch.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  }
}
